#-----------------------------------------
#Author: me
#v.0.0.2 - Added rotate-edges func
#v.0.0.3 - Fixing rotate-edges func
#have fun
#-----------------------------------------


import numpy as np
import random as rn
from collections import Counter

green = np.ones((3,3)).astype('<U1')
green[:] = 'g'
orange = np.ones((3,3)).astype('<U1')
orange[:] = 'o'
blue = np.ones((3,3)).astype('<U1')
blue[:] = 'b'
red = np.ones((3,3)).astype('<U1')
red[:] = 'r'
yellow = np.ones((3,3)).astype('<U1')
yellow[:] = 'y'
white = np.ones((3,3)).astype('<U1')
white[:] = 'w'

position = [
    {'front':green,'back':blue},
    {'left':orange,'right':red},
    {'top':white,'bot':yellow},
    ]
#pp = position[1]
def rotate_all(position):
    side = input('Enter side for rotate:\n')
    chg_ptn = {
        'left':[
            {'front':position[1]['right'],'back':position[1]['left']},
            {'left':position[0]['front'],'right':position[0]['back']},
            {'top':position[2]['top'],'bot':position[2]['bot']},
            ],
        'right':[
            {'front':position[1]['left'],'back':position[1]['right']},
            {'left':position[0]['back'],'right':position[0]['front']},
            {'top':position[2]['top'],'bot':position[2]['bot']},
            ],
        'up':[
            {'front':position[2]['bot'],'back':position[2]['top']},
            {'left':position[1]['left'],'right':position[1]['right']},
            {'top':position[0]['front'],'bot':position[0]['back']},
            ],
        'down':[
            {'front':position[2]['top'],'back':position[2]['bot']},
            {'left':position[1]['left'],'right':position[1]['right']},
            {'top':position[0]['back'],'bot':position[0]['front']},
            ],
        'reverse':[
            {'front':position[0]['back'],'back':position[0]['front']},
            {'left':position[1]['right'],'right':position[1]['left']},
            {'top':position[2]['top'],'bot':position[2]['bot']},
            ],
        'around':[
            {'front':position[0]['back'],'back':position[0]['front']},
            {'left':position[1]['left'],'right':position[1]['right']},
            {'top':position[2]['bot'],'bot':position[2]['top']},
            ],
        }
               
    position = chg_ptn[side]
    return position

def rotate_edge(position):
    chg_ptn = {
        "top":{
            "left":[
                {
                    "front":np.array([
                        position[1]['right'][0,:],
                        position[0]['front'][1,:],
                        position[0]['front'][2,:],
                    ]),
                    "back":np.array([
                        position[1]['left'][0,:],
                        position[0]['back'][1,:],
                        position[0]['back'][2,:],
                    ])
                },
                {
                    "left":np.array([
                        position[0]['front'][0,:],
                        position[1]['left'][1,:],
                        position[1]['left'][2,:],
                    ]),
                    "right":np.array([
                        position[0]['back'][0,:],
                        position[1]['right'][1,:],
                        position[1]['right'][2,:],
                    ])
                },
                {
                    "top":np.array([
                        position[2]['top'][2],
                        position[2]['top'][1],
                        position[2]['top'][0],
                    ]).transpose(),
                    "bot":position[2]['bot']
                }
            ],
            "right":[
                {
                    "front":np.array([
                        position[1]['left'][0,:],
                        position[0]['front'][1,:],
                        position[0]['front'][2,:],
                    ]),
                    "back":np.array([
                        position[1]['right'][0,:],
                        position[0]['back'][1,:],
                        position[0]['back'][2,:],
                    ])
                },
                {
                    "left":np.array([
                        position[0]['back'][0,:],
                        position[1]['left'][1,:],
                        position[1]['left'][2,:],
                    ]),
                    "right":np.array([
                        position[0]['front'][0,:],
                        position[1]['right'][1,:],
                        position[1]['right'][2,:],
                    ])
                },
                {
                    "top":np.array([
                        position[2]['top'][0,::-1],
                        position[2]['top'][1,::-1],
                        position[2]['top'][2,::-1],
                    ]).transpose(),
                    "bot":position[2]['bot']
                }
            ]
        },
        "mid":{
            "left":[
                {
                    "front":np.array([
                        position[0]['front'][0,:],
                        position[1]['right'][1,:],
                        position[0]['front'][2,:],
                    ]),
                    "back":np.array([
                        position[0]['back'][0,:],
                        position[1]['left'][1,:],
                        position[0]['back'][2,:],
                    ])
                },
                {
                    "left":np.array([
                        position[1]['left'][0,:],
                        position[0]['front'][1,:],
                        position[1]['left'][2,:],
                    ]),
                    "right":np.array([
                        position[1]['right'][0,:],
                        position[0]['back'][1,:],
                        position[1]['right'][2,:],
                    ])
                },
                {
                    "top":position[2]['top'],
                    "bot":position[2]['bot']
                }
            ],
            "right":[
                {
                    "front":np.array([
                        position[0]['front'][0,:],
                        position[1]['left'][1,:],
                        position[0]['front'][2,:],
                    ]),
                    "back":np.array([
                        position[0]['back'][0,:],
                        position[1]['right'][1,:],
                        position[0]['back'][2,:],
                    ])
                },
                {
                    "left":np.array([
                        position[1]['left'][0,:],
                        position[0]['back'][1,:],
                        position[1]['left'][2,:],
                    ]),
                    "right":np.array([
                        position[1]['right'][0,:],
                        position[0]['front'][1,:],
                        position[1]['right'][2,:],
                    ])
                },
                {
                    "top":position[2]['top'],
                    "bot":position[2]['bot']
                }
            ]
        },
        "bot":{
            "left":[
                {
                    "front":np.array([
                        position[0]['front'][0,:],
                        position[0]['front'][1,:],
                        position[1]['right'][2,:],
                    ]),
                    "back":np.array([
                        position[0]['back'][0,:],
                        position[0]['back'][1,:],
                        position[1]['left'][2,:],
                    ])
                },
                {
                    "left":np.array([
                        position[1]['left'][0,:],
                        position[1]['left'][1,:],
                        position[0]['front'][2,:],
                    ]),
                    "right":np.array([
                        position[1]['right'][0,:],
                        position[1]['right'][1,:],
                        position[0]['back'][2,:],
                    ])
                },
                {
                    "top":position[2]['top'],
                    "bot":np.array([
                        position[2]['bot'][:,2],
                        position[2]['bot'][:,1],
                        position[2]['bot'][:,0],
                    ]),
                }
            ],
            "right":[
                {
                    "front":np.array([
                        position[0]['front'][0,:],
                        position[0]['front'][1,:],
                        position[1]['left'][2,:],
                    ]),
                    "back":np.array([
                        position[0]['back'][0,:],
                        position[0]['back'][1,:],
                        position[1]['right'][2,:],
                    ])
                },
                {
                    "left":np.array([
                        position[1]['left'][0,:],
                        position[1]['left'][1,:],
                        position[0]['back'][2,:],
                    ]),
                    "right":np.array([
                        position[1]['right'][0,:],
                        position[1]['right'][1,:],
                        position[0]['front'][2,:],
                    ])
                },
                {
                    "top":position[2]['top'],
                    "bot":np.array([
                        position[2]['bot'][::-1,0],
                        position[2]['bot'][::-1,1],
                        position[2]['bot'][::-1,2],
                    ]),
                }
            ]
        },
        "left":{
            "up":[
                {
                    "front":np.array([
                        position[2]['bot'][:,0],
                        position[0]['front'][:,1],
                        position[0]['front'][:,2],
                    ]).transpose(),
                    "back":np.array([
                        position[0]['back'][:,0],
                        position[0]['back'][:,1],
                        position[2]['top'][::-1,0],
                    ]).transpose()
                },
                {
                    "left":np.array([
                        position[1]['left'][0,::-1],
                        position[1]['left'][1,::-1],
                        position[1]['left'][2,::-1],
                    ]).transpose(),
                    "right":position[1]['right']
                },
                {
                    "top":np.array([
                        position[0]['front'][:,0],
                        position[2]['top'][:,1],
                        position[2]['top'][:,2],
                    ]).transpose(),
                    "bot":np.array([
                        position[0]['back'][::-1,2],
                        position[2]['bot'][:,1],
                        position[2]['bot'][:,2],
                    ]).transpose()
                },
            ],
            "down":[
                {
                    "front":np.array([
                        position[2]['top'][:,0],
                        position[0]['front'][:,1],
                        position[0]['front'][:,2],
                    ]).transpose(),
                    "back":np.array([
                        position[0]['back'][:,0],
                        position[0]['back'][:,1],
                        position[2]['bot'][::-1,0],
                    ]).transpose()
                },
                {
                    "left":np.array([
                        position[1]['left'][2],
                        position[1]['left'][1],
                        position[1]['left'][0],
                    ]).transpose(),
                    "right":position[1]['right']
                },
                {
                    "top":np.array([
                        position[0]['back'][::-1,2],
                        position[2]['top'][:,1],
                        position[2]['top'][:,2],
                    ]).transpose(),
                    "bot":np.array([
                        position[0]['front'][:,0],
                        position[2]['bot'][:,1],
                        position[2]['bot'][:,2],
                    ]).transpose()
                },
            ],
        },
        "center":{
            "up":[
                {
                    "front":np.array([
                        position[0]['front'][:,0],
                        position[2]['bot'][:,1],
                        position[0]['front'][:,2],
                    ]).transpose(),
                    "back":np.array([
                        position[0]['back'][:,0],
                        position[2]['top'][::-1,1],
                        position[0]['back'][:,2],
                    ]).transpose()
                },
                {
                    "left":position[1]['left'],
                    "right":position[1]['right']
                },
                {
                    "top":np.array([
                        position[2]['top'][:,0],
                        position[0]['front'][:,1],
                        position[2]['top'][:,2],
                    ]).transpose(),
                    "bot":np.array([
                        position[2]['bot'][:,0],
                        position[0]['back'][::-1,1],
                        position[2]['bot'][:,2],
                    ]).transpose()
                },
            ],
            "down":[
                {
                    "front":np.array([
                        position[0]['front'][:,0],
                        position[2]['top'][:,1],
                        position[0]['front'][:,2],
                    ]).transpose(),
                    "back":np.array([
                        position[0]['back'][:,0],
                        position[2]['bot'][:,1],
                        position[0]['back'][:,2],
                    ]).transpose()
                },
                {
                    "left":position[1]['left'],
                    "right":position[1]['right']
                },
                {
                    "top":np.array([
                        position[2]['top'][:,0],
                        position[0]['back'][:,1],
                        position[2]['top'][:,2],
                    ]).transpose(),
                    "bot":np.array([
                        position[2]['bot'][:,0],
                        position[0]['front'][:,1],
                        position[2]['bot'][:,2],
                    ]).transpose()
                },
            ],
        },
        "right":{
            "up":[
                {
                    "front":np.array([
                        position[0]['front'][:,0],
                        position[0]['front'][:,1],
                        position[2]['bot'][:,2],
                    ]).transpose(),
                    "back":np.array([
                        position[2]['top'][::-1,2],
                        position[0]['back'][:,1],
                        position[0]['back'][:,2],
                    ]).transpose()
                },
                {
                    "left":position[1]['left'],
                    "right":np.array([
                        position[1]['right'][::-1,0],
                        position[1]['right'][::-1,1],
                        position[1]['right'][::-1,2],
                    ]),
                },
                {
                    "top":np.array([
                        position[2]['top'][:,0],
                        position[2]['top'][:,1],
                        position[0]['front'][:,2],
                    ]).transpose(),
                    "bot":np.array([
                        position[2]['bot'][:,0],
                        position[2]['bot'][:,1],
                        position[0]['back'][::-1,0],
                    ]).transpose()
                },
            ],
            "down":[
                {
                    "front":np.array([
                        position[0]['front'][:,0],
                        position[0]['front'][:,1],
                        position[2]['top'][:,2],
                    ]).transpose(),
                    "back":np.array([
                        position[2]['bot'][::-1,2],
                        position[0]['back'][:,1],
                        position[0]['back'][:,2],
                    ]).transpose()
                },
                {
                    "left":position[1]['left'],
                    "right":np.array([
                        position[1]['right'][0,::-1],
                        position[1]['right'][1,::-1],
                        position[1]['right'][2,::-1],
                    ]).transpose(),
                },
                {
                    "top":np.array([
                        position[2]['top'][:,0],
                        position[2]['top'][:,1],
                        position[0]['back'][::-1,0],
                    ]).transpose(),
                    "bot":np.array([
                        position[2]['bot'][:,0],
                        position[2]['bot'][:,1],
                        position[0]['front'][:,2],
                    ]).transpose()
                },
            ],
        },
    }

    row_col = input(f"Enter which row or column to rotate {list(chg_ptn.keys())}:\n")
    side = input(f"Enter side for rotate {list(chg_ptn[row_col].keys())}:\n")

    position = chg_ptn[row_col][side]
    return position

while True:
    position = rotate_edge(position)
    print(position[0]['front'])
    print(position[0]['back'])
    print(position[1]['left'])
    print(position[1]['right'])
    print(position[2]['top'])
    print(position[2]['bot'])

